version: "3.8"

services:
  simulator:
    build: 
      context: ./simulator_service
      dockerfile: Dockerfile
    container_name: simulator_service
    ports:
      - "5050:5000"
    environment:
      - SIMULATOR_URL=http://simulator:5000/simulate
    volumes:
      - ./simulator_service:/app
    networks:
      - app-net  

  django:
    build: 
      context: ./QuantumSoup
      dockerfile: Dockerfile
    container_name: django_app
    # ports:
    #   - "8000:8000"
    volumes:
      - ./QuantumSoup:/code
    environment:
      - SIMULATOR_URL=http://simulator:5000/simulate
      - USE_GPU=0
    depends_on:
      - simulator
    networks:
      - app-net

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf 
    depends_on:
      - django
    networks:
      - app-net

networks:
  app-net:
    driver: bridge